import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SidebarMenu from "@/components/Sidebar-menu";
import Header from "@/components/Header";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased  ",
          fontSans.variable
        )}>
        <Header />
        <SidebarMenu />
        {/* <SidebarMenu /> */}
        {children}
      </body>
    </html>
  );
}
